// Generated by gencpp from file lab4/oint_control_srv.msg
// DO NOT EDIT!


#ifndef LAB4_MESSAGE_OINT_CONTROL_SRV_H
#define LAB4_MESSAGE_OINT_CONTROL_SRV_H

#include <ros/service_traits.h>


#include <lab4/oint_control_srvRequest.h>
#include <lab4/oint_control_srvResponse.h>


namespace lab4
{

struct oint_control_srv
{

typedef oint_control_srvRequest Request;
typedef oint_control_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct oint_control_srv
} // namespace lab4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab4::oint_control_srv > {
  static const char* value()
  {
    return "3217da37e7b93e31d3fd5f2778f26983";
  }

  static const char* value(const ::lab4::oint_control_srv&) { return value(); }
};

template<>
struct DataType< ::lab4::oint_control_srv > {
  static const char* value()
  {
    return "lab4/oint_control_srv";
  }

  static const char* value(const ::lab4::oint_control_srv&) { return value(); }
};


// service_traits::MD5Sum< ::lab4::oint_control_srvRequest> should match 
// service_traits::MD5Sum< ::lab4::oint_control_srv > 
template<>
struct MD5Sum< ::lab4::oint_control_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab4::oint_control_srv >::value();
  }
  static const char* value(const ::lab4::oint_control_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab4::oint_control_srvRequest> should match 
// service_traits::DataType< ::lab4::oint_control_srv > 
template<>
struct DataType< ::lab4::oint_control_srvRequest>
{
  static const char* value()
  {
    return DataType< ::lab4::oint_control_srv >::value();
  }
  static const char* value(const ::lab4::oint_control_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab4::oint_control_srvResponse> should match 
// service_traits::MD5Sum< ::lab4::oint_control_srv > 
template<>
struct MD5Sum< ::lab4::oint_control_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab4::oint_control_srv >::value();
  }
  static const char* value(const ::lab4::oint_control_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab4::oint_control_srvResponse> should match 
// service_traits::DataType< ::lab4::oint_control_srv > 
template<>
struct DataType< ::lab4::oint_control_srvResponse>
{
  static const char* value()
  {
    return DataType< ::lab4::oint_control_srv >::value();
  }
  static const char* value(const ::lab4::oint_control_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB4_MESSAGE_OINT_CONTROL_SRV_H
